version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    build: .
    container_name: celery
    volumes: ['.:/home/app']
    command: celery -A tasks worker --concurrency=10 --loglevel=INFO
    depends_on:
      - rabbitmq

  flower:
    image: mher/flower:2.0
    container_name: flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - celery
      - rabbitmq

  app:
    build: .
    container_name: app
    command: gunicorn --bind :8000 --workers 3 server:app
    volumes: ['.:/home/app']
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - celery
